4. Add support for pipeline - 1. Make the plugin support pipeline with basic function
jenkinsci/parasoft-findings-plugin pull request #28
Opened 2023-07-10 02:03 UTC by lli-parasoft

2023-07-10 03:16 UTC, awang-parasoft requested changes

2023-07-10 03:16 UTC, awang-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +    private static final String DEFAULT_PATTERN = "**/coverage.xml";
Maybe we can change the access modifier of these constants in coverage recorder to package-private(no modifier) and use them in this class, then we don't need to define them here.

2023-07-10 03:16 UTC, awang-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +            return UNUSED;
To keep consistency with free-style job, we also need to delete temporary coverage directories after the coverage is published to Jenkins.

2023-07-10 03:16 UTC, awang-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +            coverageStep.start(stepContext).getContext().get(TaskListener.class);
Is this line necessary?

2023-07-10 03:16 UTC, awang-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +            return "Record Parasoft code coverage results";
We need to use localized message here. See the same method in coverage recorder.

2023-07-12 06:10 UTC, awang-parasoft reviewed
OK

2023-07-18 06:48 UTC, yshi-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +            Method performMethod =
Please add a comment to explain the reason for using Reflection here.

2023-07-18 06:49 UTC, yshi-parasoft commented on src/main/java/com/parasoft/findings/jenkins/coverage/ParasoftCoverageStep.java
> +                    ReflectionUtils.findMethod(CoverageRecorder.class, "perform", Run.class, FilePath.class,
Please add "//$NON-NLS-1$" for all places using strings but have no localization

2023-07-18 07:16 UTC, merged